#!C:\Users\louka\Documents\YNOV\B2\Python Data\Data\mon_environnement\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
